### ISSUE TITLE
Reset Password stylings

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-workflows#51]
seen in https://pxblue-temp.web.app/auth/reset-password?code=DEADBEEF&email=resetPassword@email.com 		
* the top divider does not go full width
* The check icon: should use gray200, icon sizes 18x18
* Password reset success screen appears to have a typo in the code:
![image](https://user-images.githubusercontent.com/8997218/103788958-71dc6c00-500d-11eb-99b2-d2ac34c4bc07.png)

**Comment by emclaug2** [comment]
<img width="598" alt="Screen Shot 2021-01-20 at 10 46 44 AM" src="https://user-images.githubusercontent.com/6538289/105199642-fa2e3700-5b0c-11eb-9918-14b7c9bf427c.png">
<img width="557" alt="Screen Shot 2021-01-20 at 10 47 14 AM" src="https://user-images.githubusercontent.com/6538289/105199645-fac6cd80-5b0c-11eb-82d8-14ff5121a567.png">
