### ISSUE TITLE
Duplicate documentation section

### ISSUE THREAD

**Issue by joebochill** [pxblue/angular-workflows#75]
#### Describe the bug
There is a section of the documentation that appears in two places with slightly different content.

#### What is the expected behavior?
Only one section with the correct information.

#### What are the steps to reproduce?
1. Open the services readme and scroll down to the authSecurityService

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/115384856-805a2800-a1a5-11eb-81e0-a1b3eb5ccda6.png)

**Comment by emclaug2** [comment]
This is fixed in #73
