### ISSUE TITLE
Spanish Translations need Tweaked

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-workflows#86]
#### Describe the bug
Spanish Translations do not match React's 

#### What is the expected behavior?
The spanish translations should be as close as possible to React. 

#### What are the steps to reproduce?
See the `src/translations/spanish` file.

#### Environment

Chrome, Windows

**Comment by huayunh** [comment]
We can attempt to make ng and React auth shared translation to have the same variable name to reuse the translation. 

Can possibly be part of the translation audit story (make sure all the translations are used somewhere, implicitly or explicitly)

@huayunh to make a new JIRA story for this

**Comment by huayunh** [comment]
PXBLUE-2134
